### ISSUE TITLE
base

### ISSUE THREAD

**Issue by himvins** [himvins/flow-data-across-js-files#211]
I apologize for the oversight. Let me make the necessary adjustments to ensure that the popover does not close when the mouse is moved outside. Here's the updated code:

```html
<div class="popover__wrapper" onmouseenter="openPopover()" onmouseleave="closePopover()">
  <h2 class="popover__title">Hover:me</h2>
  <div class="popover__content" id="popoverContent">
    <p class="popover__message">Joseph Francis "Joey" Tribbiani, Jr.</p>
    <img alt="Joseph Francis Joey Tribbiani, Jr." src="https://media.giphy.com/media/11SIBu3s72Co8w/giphy.gif">
    <span class="close-btn" onclick="closePopover()">Close</span>
  </div>
</div>
```

```css
/* Base styling */
body {
  background-color: lightgrey;
  max-width: 768px;
  margin: 0 auto;
  padding: 1em 0;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
}

/* Popover styling */
a {
  text-decoration: none;
}

.popover__title {
  font-size: 24px;
  line-height: 36px;
  text-decoration: none;
  color: rgb(228, 68, 68);
  text-align: center;
  padding: 15px 0;
}

.popover__wrapper {
  position: relative;
  margin-top: 1.5rem;
  display: inline-block;
}

.popover__content {
  opacity: 0;
  visibility: hidden;
  position: absolute;
  left: 50%;
  transform: translate(-50%, 10px);
  background-color: #bfbfbf;
  padding: 1.5rem;
  box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.26);
  width: auto;
}

.popover__content:before {
  position: absolute;
  z-index: -1;
  content: "";
  right: calc(50% - 10px);
  top: -8px;
  border-style: solid;
  border-width: 0 10px 10px 10px;
  border-color: transparent transparent #bfbfbf transparent;
  transition-duration: 0.3s;
  transition-property: transform;
}

.popover__wrapper:hover .popover__content {
  z-index: 10;
  opacity: 1;
  visibility: visible;
  transform: translate(-50%, -20px);
  transition: all 0.5s cubic-bezier(0.75, -0.02, 0.2, 0.97);
}

.popover__message {
  text-align: center;
}

.close-btn {
  cursor: pointer;
  position: absolute;
  bottom: 10px;
  left: 50%;
  transform: translateX(-50%);
  color: #555;
  font-size: 14px;
}
```

I've added `onmouseenter` and `onmouseleave` attributes to the `<div>` element, and modified the CSS to ensure the popover stays open when the mouse is moved out.
