### ISSUE TITLE
Css test

### ISSUE THREAD

**Issue by himvins** [himvins/flow-data-across-js-files#241]
The `overflow` property doesn't work as expected with `display: table` due to the way the CSS `display` property interacts with table layouts. When an element is styled as a table, its children (rows and cells) are treated differently compared to block or inline elements, which can cause issues with properties like `overflow`.

To achieve the desired overflow behavior while maintaining a table-like layout, you can use alternative methods such as:

1. **Flexbox**: Use Flexbox to create a table-like layout with better control over overflow.

```html
<div class="table">
  <div class="table-row">
    <div class="table-cell">Content</div>
    <div class="table-cell">Content</div>
  </div>
  <!-- More rows -->
</div>
```

```css
.table {
  display: flex;
  flex-direction: column;
}

.table-row {
  display: flex;
}

.table-cell {
  flex: 1;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}
```

2. **Grid Layout**: Use CSS Grid to create a table-like structure with support for overflow.

```html
<div class="grid-table">
  <div class="grid-cell">Content</div>
  <div class="grid-cell">Content</div>
  <!-- More cells -->
</div>
```

```css
.grid-table {
  display: grid;
  grid-template-columns: repeat(2, 1fr); /* Adjust as needed */
  overflow: hidden;
}

.grid-cell {
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}
```

3. **Nested Divs**: If you must use a table, wrap the table in a `div` and apply `overflow` to that `div`.

```html
<div class="wrapper">
  <table class="table">
    <tr>
      <td>Content</td>
      <td>Content</td>
    </tr>
    <!-- More rows -->
  </table>
</div>
```

```css
.wrapper {
  overflow: auto;
  max-height: 200px; /* or desired height */
}

.table {
  width: 100%;
}
```

These methods allow you to control overflow behavior more effectively while mimicking a table layout.
