### ISSUE TITLE
I apologize for not including styling in the previous code. Below, I'll provide some basic styling for the dynamic questionnaire to make it more visually appealing. You can customize it further according to your preferences.

Step 6

### ISSUE THREAD

**Issue by himvins** [himvins/flow-data-across-js-files#61]
I apologize for not including styling in the previous code. Below, I'll provide some basic styling for the dynamic questionnaire to make it more visually appealing. You can customize it further according to your preferences.

Step 6: Styling (questionnaire.component.css)
Add the following CSS to the `questionnaire.component.css` file:

```css
/* Styling for the container */
.question-container {
  margin: 20px;
  padding: 20px;
  border: 1px solid #ccc;
  border-radius: 5px;
  background-color: #f9f9f9;
}

/* Styling for questions and input elements */
.question-container h2 {
  margin-bottom: 10px;
}

.question-container input[type="text"],
.question-container select,
.question-container input[type="radio"],
.question-container input[type="checkbox"] {
  margin-right: 10px;
}

/* Styling for buttons */
.question-container button {
  margin-top: 10px;
  padding: 8px 16px;
  border: none;
  border-radius: 5px;
  background-color: #007bff;
  color: #fff;
  cursor: pointer;
}

.question-container button:hover {
  background-color: #0056b3;
}

/* Styling for the summary page */
.summary-container {
  margin: 20px;
  padding: 20px;
  border: 1px solid #ccc;
  border-radius: 5px;
  background-color: #f9f9f9;
}

.summary-container h2 {
  margin-bottom: 10px;
}

.summary-container ul {
  padding: 0;
  list-style-type: none;
}

.summary-container li {
  margin-bottom: 5px;
}

/* Styling for the Restart button on the summary page */
.summary-container button {
  margin-top: 10px;
  padding: 8px 16px;
  border: none;
  border-radius: 5px;
  background-color: #dc3545;
  color: #fff;
  cursor: pointer;
}

.summary-container button:hover {
  background-color: #b02a37;
}
```

Make sure to include this CSS file in the `questionnaire.component.ts` file by updating the `styleUrls` array:

**questionnaire.component.ts**
```typescript
import { Component, OnInit } from '@angular/core';
import { QuestionnaireService } from '../services/questionnaire.service';
import { Question } from '../models/question.model';
import { Answer } from '../models/answer.model';

@Component({
  selector: 'app-questionnaire',
  templateUrl: './questionnaire.component.html',
  styleUrls: ['./questionnaire.component.css']
})
export class QuestionnaireComponent implements OnInit {
  // ... Rest of the code remains unchanged ...
}
```

With the added styling, your dynamic questionnaire will look more visually appealing and have a sleek design.

Remember that this is just a basic styling to get you started. You can further customize the styles, add animations, and enhance the design as per your project's requirements and your creativity.
