### ISSUE TITLE
Creating a conversation cloud and adding a bot avatar to the questionnaire component can definitely enhance the user experience and give the feeling of interacting with a bot. To achieve this, you can use HTML, CSS, and possibly some graphics or images. Below, I'll provide you with a basic example of how you can modify the questionnaire component template to add these elements.

Step 1

### ISSUE THREAD

**Issue by himvins** [himvins/flow-data-across-js-files#67]
Creating a conversation cloud and adding a bot avatar to the questionnaire component can definitely enhance the user experience and give the feeling of interacting with a bot. To achieve this, you can use HTML, CSS, and possibly some graphics or images. Below, I'll provide you with a basic example of how you can modify the questionnaire component template to add these elements.

Step 1: Add Bot Avatar Image
First, you'll need to prepare a bot avatar image (e.g., a PNG or SVG file) to use in your component. Save the bot avatar image in the `assets` folder of your Angular project. For example, you can create a file named `bot-avatar.png` in the `assets` folder.

Step 2: Update the Questionnaire Component Template
Update the `questionnaire.component.html` file to include the conversation cloud and the bot avatar image.

**questionnaire.component.html**
```html
<div class="questionnaire-container">
  <!-- Conversation Cloud -->
  <div class="cloud-container">
    <div class="cloud">
      <div class="question-text">{{ currentQuestion?.text }}</div>
      <!-- Question Input Controls (Use appropriate CSS classes for styling) -->
      <!-- ... Rest of the input elements ... -->
      <div *ngIf="currentQuestion">
        <button (click)="onNextClick()" class="btn btn-primary">Next</button>
        <button (click)="onPreviousClick()" class="btn btn-secondary">Previous</button>
      </div>
    </div>
  </div>

  <!-- Bot Avatar -->
  <div class="bot-avatar">
    <img src="assets/bot-avatar.png" alt="Bot Avatar" />
  </div>
</div>

<div class="summary-container" *ngIf="showSummary">
  <!-- ... Rest of the summary container ... -->
  <button (click)="onReset()" class="btn btn-danger">Restart</button>
</div>
```

Step 3: Add CSS Styling
Now, you'll need to update the CSS styles to create the conversation cloud and position the bot avatar correctly.

**questionnaire.component.css**
```css
.questionnaire-container {
  position: relative;
}

/* Styling for the conversation cloud */
.cloud-container {
  position: relative;
  margin: 20px;
  padding: 20px;
  border-radius: 15px;
  background-color: #f0f0f0;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
}

.cloud {
  padding: 10px;
}

.question-text {
  font-size: 18px;
  margin-bottom: 10px;
}

/* Styling for the bot avatar */
.bot-avatar {
  position: absolute;
  bottom: 0;
  right: 10px;
  width: 80px;
  height: 80px;
}
```

With these modifications, you should see the conversation cloud around the questions, and the bot avatar at the bottom-right corner of the questionnaire component. The conversation cloud will give the feel of questions being asked by a bot.

Feel free to adjust the CSS styles, bot avatar size, and positioning to match your design preferences. Additionally, you can add animations or other effects to make the bot avatar more interactive and engaging.
