### ISSUE TITLE
Creating a secondary button in CSS typically involves defining styles that differentiate it from the primary button. Secondary buttons are often used as less prominent options compared to the primary buttons on a webpage. Below is an example of CSS code to create a simple secondary button

### ISSUE THREAD

**Issue by himvins** [himvins/flow-data-across-js-files#71]
Creating a secondary button in CSS typically involves defining styles that differentiate it from the primary button. Secondary buttons are often used as less prominent options compared to the primary buttons on a webpage. Below is an example of CSS code to create a simple secondary button:

```html
<!DOCTYPE html>
<html>
<head>
  <title>Secondary Button Example</title>
  <link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
  <button class="primary-btn">Primary Button</button>
  <button class="secondary-btn">Secondary Button</button>
</body>
</html>
```

```css
/* styles.css */

/* Primary Button Styles */
.primary-btn {
  background-color: #007bff; /* Use your desired primary button color */
  color: #fff; /* Text color */
  padding: 10px 20px; /* Add padding to create a comfortable button size */
  border: none; /* Remove default button border */
  border-radius: 4px; /* Rounded corners */
  font-size: 16px; /* Font size of the button text */
  cursor: pointer; /* Change the cursor to a pointer on hover */
}

.primary-btn:hover {
  background-color: #0056b3; /* Change the background color on hover */
}

/* Secondary Button Styles */
.secondary-btn {
  background-color: #f0f0f0; /* Use your desired secondary button color */
  color: #333; /* Text color */
  padding: 10px 20px; /* Add padding to create a comfortable button size */
  border: none; /* Remove default button border */
  border-radius: 4px; /* Rounded corners */
  font-size: 16px; /* Font size of the button text */
  cursor: pointer; /* Change the cursor to a pointer on hover */
}

.secondary-btn:hover {
  background-color: #dcdcdc; /* Change the background color on hover */
}
```

In this example, we have created a simple CSS style for both primary and secondary buttons. The primary button has a blue background color, and the secondary button has a light gray background color. Feel free to modify the colors, sizes, and other properties to fit your specific design requirements.
