### ISSUE TITLE
To create a text box with a Bootstrap-like style, you can use CSS to mimic the appearance of Bootstrap's default text input. Bootstrap's text inputs typically have rounded corners, a subtle box shadow, and a specific font style. Below is an example of CSS code to achieve this

### ISSUE THREAD

**Issue by himvins** [himvins/flow-data-across-js-files#72]
To create a text box with a Bootstrap-like style, you can use CSS to mimic the appearance of Bootstrap's default text input. Bootstrap's text inputs typically have rounded corners, a subtle box shadow, and a specific font style. Below is an example of CSS code to achieve this:

```html
<!DOCTYPE html>
<html>
<head>
  <title>Text Box Example</title>
  <link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
  <input type="text" class="bootstrap-like-textbox" placeholder="Enter text here">
</body>
</html>
```

```css
/* styles.css */

.bootstrap-like-textbox {
  display: block;
  width: 100%;
  padding: 10px 15px;
  font-size: 16px;
  line-height: 1.5;
  color: #555;
  background-color: #fff;
  background-clip: padding-box;
  border: 1px solid #ccc;
  border-radius: 4px;
  transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
}

.bootstrap-like-textbox::placeholder {
  color: #999;
}

.bootstrap-like-textbox:focus {
  border-color: #80bdff;
  outline: 0;
  box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
}
```

In this example, we create a class named `bootstrap-like-textbox` and apply it to the text input element. The styles include the use of border-radius, box-shadow, and transitions to mimic Bootstrap's text input appearance. The `::placeholder` pseudo-element is used to style the placeholder text, and the `:focus` pseudo-class is used to modify the appearance when the text box is in focus.

The above code will give you a text box with a Bootstrap-like style. Feel free to adjust the colors, padding, or other properties to match your specific needs and design preferences.
