### ISSUE TITLE
Sure! To style radio buttons similarly to Bootstrap, you can use CSS to create a custom design. Bootstrap-like radio buttons often have a circular shape and a different appearance when selected. Below is an example of CSS code to achieve this

### ISSUE THREAD

**Issue by himvins** [himvins/flow-data-across-js-files#73]
Sure! To style radio buttons similarly to Bootstrap, you can use CSS to create a custom design. Bootstrap-like radio buttons often have a circular shape and a different appearance when selected. Below is an example of CSS code to achieve this:

```html
<!DOCTYPE html>
<html>
<head>
  <title>Radio Button Example</title>
  <link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
  <label class="bootstrap-like-radio">
    <input type="radio" name="option" value="option1">
    Option 1
  </label>
  <label class="bootstrap-like-radio">
    <input type="radio" name="option" value="option2">
    Option 2
  </label>
</body>
</html>
```

```css
/* styles.css */

.bootstrap-like-radio {
  display: inline-block;
  position: relative;
  padding-left: 30px;
  margin-right: 15px;
  cursor: pointer;
  font-size: 16px;
}

.bootstrap-like-radio input[type="radio"] {
  opacity: 0;
  position: absolute;
  left: 0;
  top: 0;
}

.bootstrap-like-radio span {
  position: absolute;
  left: 0;
  top: 0;
  width: 20px;
  height: 20px;
  border: 2px solid #007bff; /* Use your desired color for the border */
  border-radius: 50%;
}

.bootstrap-like-radio input[type="radio"]:checked + span {
  background-color: #007bff; /* Use the same color as the border when selected */
}
```

In this example, we create a class named `bootstrap-like-radio` and apply it to the label element wrapping the radio input and its associated text. The styles include the use of a circular border to mimic Bootstrap's radio button appearance. We also hide the default radio input by setting its opacity to 0 and create a circular span element to represent the custom radio button. When the radio button is checked, we change the background color of the circular span to indicate its selection.

Note that you can modify the color and size of the radio button by adjusting the border and background-color properties. Additionally, you can further customize the styles to match your specific design requirements.
