### ISSUE TITLE
I apologize for the oversight. It seems that the custom radio button styles are not being applied correctly. Let's modify the CSS to fix the issue and ensure that the radio buttons are visible

### ISSUE THREAD

**Issue by himvins** [himvins/flow-data-across-js-files#74]
I apologize for the oversight. It seems that the custom radio button styles are not being applied correctly. Let's modify the CSS to fix the issue and ensure that the radio buttons are visible:

```html
<!DOCTYPE html>
<html>
<head>
  <title>Radio Button Example</title>
  <link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
  <label class="bootstrap-like-radio">
    <input type="radio" name="option" value="option1">
    <span class="checkmark"></span>
    Option 1
  </label>
  <label class="bootstrap-like-radio">
    <input type="radio" name="option" value="option2">
    <span class="checkmark"></span>
    Option 2
  </label>
</body>
</html>
```

```css
/* styles.css */

.bootstrap-like-radio {
  display: inline-block;
  position: relative;
  padding-left: 30px;
  margin-right: 15px;
  cursor: pointer;
  font-size: 16px;
}

.bootstrap-like-radio input[type="radio"] {
  opacity: 0;
  position: absolute;
  left: 0;
  top: 0;
}

.checkmark {
  position: absolute;
  left: 0;
  top: 0;
  width: 20px;
  height: 20px;
  border: 2px solid #007bff; /* Use your desired color for the border */
  border-radius: 50%;
}

.bootstrap-like-radio input[type="radio"]:checked + .checkmark::after {
  content: "";
  position: absolute;
  top: 4px;
  left: 4px;
  width: 12px;
  height: 12px;
  background-color: #007bff; /* Use the same color as the border when selected */
  border-radius: 50%;
}
```

In this modified version, we've added a `span` element with the class `checkmark` to represent the custom radio button. When the radio button is checked, the `::after` pseudo-element is used to create a small circle inside the `span`, which indicates the selected state of the radio button.

Now, the radio buttons should be visible and styled with a circular design when checked. As before, you can adjust the color, size, and other properties to fit your specific design requirements.
