### ISSUE TITLE
Yes, you can add an overlay to the loader to prevent user interaction with the underlying content while the loader is visible. This overlay will act as a semi-transparent layer that covers the entire screen, making it visually clear that the content is disabled and the user should wait for the loading process to complete.

To achieve this, you can update the loader component's template and CSS as follows

### ISSUE THREAD

**Issue by himvins** [himvins/flow-data-across-js-files#77]
Yes, you can add an overlay to the loader to prevent user interaction with the underlying content while the loader is visible. This overlay will act as a semi-transparent layer that covers the entire screen, making it visually clear that the content is disabled and the user should wait for the loading process to complete.

To achieve this, you can update the loader component's template and CSS as follows:

**loader.component.html**:
```html
<div class="overlay">
  <div class="loader"></div>
</div>
```

**loader.component.css**:
```css
.overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.5); /* Adjust the opacity as needed */
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 9999; /* Make sure the overlay is on top of other content */
}

.loader {
  border: 4px solid #f3f3f3;
  border-top: 4px solid #3498db;
  border-radius: 50%;
  width: 40px;
  height: 40px;
  animation: spin 2s linear infinite;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
```

With this CSS update, the overlay will cover the entire screen with a semi-transparent background while the loader is displayed. The `z-index` property ensures that the overlay is positioned on top of other content, preventing user interactions with the underlying components.

When you set the `submitting` flag to `true`, the loader component will be displayed along with the overlay, visually indicating that the application is in a loading state and the user should wait for the loading process to complete.

As a result, the loader will now have an overlay to improve the user experience during loading periods.
