### ISSUE TITLE
Sure! Let's create two more button styles

### ISSUE THREAD

**Issue by himvins** [himvins/flow-data-across-js-files#81]
Sure! Let's create two more button styles: a third type with a red color and a fourth type with a shade of green. We'll align them with the primary and secondary buttons to maintain consistency. Here's the updated CSS:

```html
<!DOCTYPE html>
<html>
<head>
  <title>Custom Buttons Example</title>
  <link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
  <button class="primary-btn">Primary Button</button>
  <button class="secondary-btn">Secondary Button</button>
  <button class="red-btn">Red Button</button>
  <button class="green-btn">Green Button</button>
</body>
</html>
```

```css
/* styles.css */

/* Primary Button Styles */
.primary-btn {
  /* Existing primary button styles */
}

/* Secondary Button Styles */
.secondary-btn {
  /* Existing secondary button styles */
}

/* Red Button Styles */
.red-btn {
  background-color: #ff6666; /* Use your desired red color (lighter shade) */
  color: #fff;
  padding: 10px 20px;
  border: none;
  border-radius: 4px;
  font-size: 16px;
  cursor: pointer;
}

.red-btn:hover {
  background-color: #ff4d4d; /* Slightly darker red on hover */
}

/* Green Button Styles */
.green-btn {
  background-color: #66cc66; /* Use your desired green color (lighter shade) */
  color: #fff;
  padding: 10px 20px;
  border: none;
  border-radius: 4px;
  font-size: 16px;
  cursor: pointer;
}

.green-btn:hover {
  background-color: #59b359; /* Slightly darker green on hover */
}
```

In the above code, we've added two new button styles: `red-btn` and `green-btn`. The `red-btn` is a red-colored button with a lighter shade of red as the background and a slightly darker shade of red on hover. The `green-btn` is a green-colored button with a lighter shade of green as the background and a slightly darker shade of green on hover.

You can adjust the red and green colors to your liking by modifying the background-color and hover background-color values. By keeping the styles consistent with the primary and secondary buttons, you'll create a cohesive design for all four button types.
